### ISSUE TITLE
Improve content display 

### ISSUE THREAD

**Issue by antavelos** [antavelos/terminews#12]
Currently the display approach of the content is quite naive as it will just display the text found in every single `<p>` tag found in the HTML of the article. A more sophisticated approach should be applied in order to remove unnecessary garbage.

**Comment by mmcdole** [comment]
Perhaps one of these content extraction libraries would be worth looking at:

https://github.com/advancedlogic/GoOse
https://github.com/jlubawy/go-boilerpipe
https://github.com/thatguystone/swan

They seem to all either implement Goose HTML Content extraction, or are a port of the Boilerplate library.  You'd have to assess which of these gave the best results.

I think this would be a big improvement to the app though!

**Comment by antavelos** [comment]
I had a look on GoOse the other day and it looks quite promising. I'll check the other two as well though. Thanks a lot for the feedback! :)

**Comment by antavelos** [comment]
Improved content using the [GoOse](https://github.com/advancedlogic/GoOse) library in https://github.com/antavelos/terminews/pull/14
