### ISSUE TITLE
consider adding manpage?

### ISSUE THREAD

**Issue by creekorful** [antavelos/terminews#20]
Hello !

First of all thank your your application, I'm really loving it so far :D

https://blog.creekorful.com/2019/07/terminews/

I am working to get your application on Debian main archive, so that everyone can install it using `apt-get install`. The application will be uploaded on the archive soon, and available on the next Debian release (codename bullseye).

The only thing is: generally we should have manpage for end-user application. While I could write one only for Debian, it could be great if we write it together and publish it upstream so that people that install terminews trough Github will benefit of the manpage too.

Are you interested?

**Comment by antavelos** [comment]
Hey Aloïs,

Thanks for your interest in the app, happy you enjoy it so far! :)

I really appreciate your intention in adding the app in Debian's archive and I'd like to help on that: Let us write the manpage together. However, I've never done it before so any hint will be much welcome.

**Comment by creekorful** [comment]
There's a ton of ways of doing it, but basically if think one of these two may be interesting:

- We can write it is by adding a `--help` flag to terminews and write the help, and then use [help2man](https://www.gnu.org/software/help2man/) to generate a man page from the `--help` output.
- Write the manpage *by hand* using a tutorial like [this one](https://2buntu.com/articles/1034/how-to-write-a-manpage/) for example.

**Comment by antavelos** [comment]
Ok, let's go with the second option. I'll make a PR with a draft manpage and we can pick it up from there.
