### ISSUE TITLE
Consider adding --version flag?

### ISSUE THREAD

**Issue by creekorful** [antavelos/terminews#23]
Hello there!

I'm am packaging your application on homebrew, so that everyone using Mac OS can install it easily using brew.
The only things is: brew formulae requires a test section that make sure the application has been installed / compiled successfully.

One simple test can be running the application with --version flag and making sure the output matches the formulae version.

Do you considerate a PR adding --version flag that will simple display app version and exit?

Cheers

**Comment by antavelos** [comment]
@creekorful sure, why not? that would be great! :)
