### ISSUE TITLE
bug: manage relative URL

### ISSUE THREAD

**Issue by creekorful** [antavelos/terminews#25]
I've noticed a little bug while browsing my own RSS sources: https://blog.creekorful.com/index.xml

As you can see, the link are relative and therefore terminews is unable to open them. I think we should append the host to the link if the link is relative.

I'm be willing to do the PR, of course.

The problem is relative to this specific part of code:

https://github.com/antavelos/terminews/blob/99eb02b98f834f1f893144f913d97fbc51e71b6e/ctrl.go#L659

I've take a lot at the source code, and I have some suggestions to refactor the code a bit if you consider it! Getting rid of the global variables and make the function more state-less to ease maintenance. Would your consider it?

**Comment by antavelos** [comment]
@creekorful  Good catch! ;) Feel free to do the PR!

The app indeed needs some serious refactoring. I developed it while learning Go and the code obviously lacks cohesion. Last year I started re-writing big part of the app but never completed it...

I really appreciate your willingness to contribute and revive this app. My time this period is kinda limited but I'd be glad to review any relevant PR :)
